### ISSUE TITLE
Unable to install on MacOs High Sierra, R: 3.4.3

### ISSUE THREAD

**Issue by vitasiku** [mlampros/ClusterR#12]
I get "clang: error: unsupported option '-fopenmp'". 
MacOs: High Sierra
R: 3.4.3

Similarly to this
_Originally posted by @vitasiku in https://github.com/mlampros/ClusterR/issues/3#issuecomment-444274724_

**Comment by mlampros** [comment]
@vitasiku,

the issue that you [refer](https://github.com/mlampros/ClusterR/issues/3#issuecomment-444274724) had actually to do with an installation problem of the 'gmp' package, on which the ClusterR package [depends](https://github.com/mlampros/ClusterR/blob/master/DESCRIPTION). It was a temporary issue which is now fixed. As you can also see in the package [check results](https://cran.r-project.org/web/checks/check_results_ClusterR.html) the ClusterR package can be installed on Macintosh ([currently it's tested on  OS X 10.11.6](https://cran.r-project.org/web/checks/check_flavors.html#r-oldrel-osx-x86_64) which is the El Capitan version and CRAN uses Xcode 8.2.1, clang 4.0.0, GNU Fortran 6.1).

I use Macintosh Sierra too but it is configured with gcc support (I used brew to upgrade gcc). An extensive tutorial on how to make OpenMP and Rcpp work on Macintosh can be found [here](https://thecoatlessprofessor.com/programming/openmp-in-r-on-os-x/). Not only ClusterR but also the RcppArmadillo (on which ClusterR depends) uses internally OpenMP to improve efficiency.

I run the following examples (threads = 1 and threads = 2) on my Macintosh Sierra with the current version of ClusterR (1.1.6) and it worked error free,

```R
#----------------
# threads = 1
#----------------

library(ClusterR)
data(dietary_survey_IBS)
dat = dietary_survey_IBS[, -ncol(dietary_survey_IBS)]
dat = distance_matrix(dat, method = 'euclidean', upper = TRUE, diagonal = TRUE, threads = 1)

#----------------
# threads = 2
#----------------

dat1 = distance_matrix(dat, method = 'euclidean', upper = TRUE, diagonal = TRUE, threads = 2)

```

So, the reason that you get the openmp error is because Macintosh does not natively support OpenMP.

**Comment by vitasiku** [comment]
@mlampros thanks for the extensive reply. I will try and follow the tutorial in the link.
