### ISSUE TITLE
for Cluster_Medoids why is a Hollow Matrix required for data as dissimilarity matrix input

### ISSUE THREAD

**Issue by dhbrand** [mlampros/ClusterR#6]
Hi, 
I'm trying to use your Cluster_Medoids (CM) function to replace the Base R pam function that is currently being used in a package I'm collaborating on (PReMiuM).  My input to pam is a single vector dissimilarity matrix which does not work with your CM func.  In the help it says CM data can be a dissimilarity matrix, where the main diagonal equals 0.0 and the number of rows equals the number of columns which when I google is a hollow matrix.  I cannot find any R packages to convert to a hollow matrix.  Is there a reason for the constraint to a hollow matrix or do you know of a way to convert a vector to a hollow matrix?  Thank you.

**Comment by mlampros** [comment]
hello @dhbrand,

the reason that the *Cluster_Medoids (CM)* function accepts a dissimilarity matrix with the main diagonal to be equal to 0.0 is because *CM* was created to work with the *distance_matrix* function (again) from the ClusterR package. The *distance_matrix* function works with dissimilarities, so that way I just wanted to avoid potential problems, say a similarity matrix as input (probably with the main diagonal to be equal to 1.0). However, this can be changed in the future if new distance metrics will be added.

Concerning the conversion from a vector to a distance matrix, I think it's feasible only in the following case,

```R

# assuming I want to create a square distance matrix

set.seed(1)
vec = runif(100)
mt = matrix(vec, 10, 10)
diag(mt) = 0.0
mt

```

just for illustration on how this can be done.

However, I took a look to the *PReMiuM* package and especially the [calcOptimalClustering](https://github.com/cran/PReMiuM/blob/master/R/postProcess.R#L579) and the [calcDissimilarityMatrix](https://github.com/cran/PReMiuM/blob/master/R/postProcess.R#L532) functions. I used the example from the package documentation to come to the dimensions of the *dissimilarity matrix*,

```R

library(PReMiuM)

generateDataList <- clusSummaryBernoulliDiscrete()

inputs <- generateSampleDataFile(generateDataList)

runInfoObj<-profRegr(yModel=inputs$yModel, xModel=inputs$xModel, 
                                    nSweeps=10, nBurn=20, data=inputs$inputData, output="output", 
                                    covNames=inputs$covNames,nClusInit=15)

dissimObj<-calcDissimilarityMatrix(runInfoObj)

str(dissimObj)

```

and it gives the following dimensions for the dissimilarity matrix,

```R

$ disSimMat       : num [1:499500] 1 1 1 0.8 0.8 0.8 0.8 0.9 0.8 0.8 ...

```

The *pam* function takes also a vector as input and the documentation mentions,

*... Also a vector of length n(n-1)/2 is allowed (where n is the number of observations), and will be interpreted in the same way as the output of the above-mentioned functions...*. 

So,  in case of the *generateDataList* object the total number of observations would be 1000 and thus,

```R

n * (n-1) / 2 = 1000 * (1000 - 1) / 2 = 499500       # disSimMat's  dimensions

```

I'm not familiar with the objects returned from the *calcDissimilarityMatrix* but if the *disSimMat* object can be converted to a square matrix (as is the case for dissimilarity matrices) then you can use the *CM* function.

**Comment by dhbrand** [comment]
Thanks for the in depth reply.  You are right on with the disSimMat object.  The developer said they chose the vector method for computational efficiency.  I'm working on datasets between 15k-60k observations and around 20 features so I might not be able to convert my vector into a square matrix without running into memory constraints.   I might see if I can use the output from the main profReg function and then feed to your distance_matrix function instead of using the calcDissimiliarityMatrix function.  Thanks again.
